[package]
name = "learntask"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.20.1",  features = ["rustls-tls-webpki-roots"] }
serde = "1.0.219"
serde_json = "1.0.140"
url = "2.3"
futures-util = "0.3.31"
